<?php
/**
 * Flexslider export: multi
 */

$preset = new stdClass();
$preset->disabled = FALSE; /* Edit this to true to make a default preset disabled initially */
$preset->api_version = 1;
$preset->name = 'multi';
$preset->title = 'multi';
$preset->theme = 'classic';
$preset->imagestyle_normal = 'third';
$preset->imagestyle_thumbnail = 'third';
$preset->options = array(
  'namespace' => 'flex-',
  'selector' => '.slides > li',
  'easing' => 'swing',
  'direction' => 'horizontal',
  'reverse' => 0,
  'smoothHeight' => 0,
  'startAt' => '0',
  'animationSpeed' => '600',
  'initDelay' => '0',
  'useCSS' => 1,
  'touch' => 1,
  'video' => 0,
  'keyboard' => 1,
  'multipleKeyboard' => 0,
  'mousewheel' => 0,
  'controlsContainer' => '.flex-control-nav-container',
  'sync' => '',
  'asNavFor' => '',
  'itemWidth' => '300',
  'itemMargin' => '10',
  'minItems' => '3',
  'maxItems' => '3',
  'move' => '3',
  'animation' => 'slide',
  'slideshow' => 0,
  'slideshowSpeed' => '7000',
  'directionNav' => 1,
  'controlNav' => '1',
  'prevText' => 'Previous',
  'nextText' => 'Next',
  'pausePlay' => 0,
  'pauseText' => 'Pause',
  'playText' => 'Play',
  'randomize' => 0,
  'thumbCaptions' => 0,
  'thumbCaptionsBoth' => 0,
  'animationLoop' => 0,
  'pauseOnAction' => 1,
  'pauseOnHover' => 0,
  'manualControls' => '',
);
