# This is how to add a badge to the README file.
#[](https://github.com/backdrop/backdrop-issues/workflows/Greetings/badge.svg)

name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

# This is how to trigger a workflow on cron:
#on:
#  schedule:
#   - cron:  '0 * * * *'

# This is how to trigger a workflow when a comment is created:
#on:
#  issue_comment:
#    types: [created]

# This is how to trigger a workflow when a comment is posted on a PR
#on:
#  pull_request_review_comment:
#    types: [created, deleted]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action:
      # https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'

